### ISSUE TITLE
Fix 2d array definition

### ISSUE THREAD

**Issue by grim117reaper** [grim117reaper/Grammar_generator_for_nltk#1]
need to get the number of words and number of sentences and create a 2d array to store tokenized words in it

**Comment by sanchittechnogeek** [comment]
Create a list for each of them and then zip()

**Comment by sanchittechnogeek** [comment]
make it readable for others. pls pleb 🙏 

### For increasing its robustness
* keep the example phrases in a txt
* load that txt file into your script

just saying xD

**Comment by grim117reaper** [comment]
Issue fixed
